### ISSUE TITLE
Feature Request: fileget glob match, output to files

### ISSUE THREAD

**Issue by clay584** [simonkowallik/iHAC#1]
Downloading the file and putting it to stdout is nice, but using xargs with file redirection is problematic. It would be nice to be able to specify a glob to match N number of files and download them all directly to a local file. Also, another option to specify an output directory if different from the current directory (for example, to save files from a particular qkview to a sub-directory, create if it doesn't exist).

Example:
`ihac-fileget -o ./EXTERNAL-F5-A 12345678 */bigip.conf`
This would find all file paths ending in bigip.conf and download them all to ./EXTERNAL-F5-A directory.

**Comment by simonkowallik** [comment]
@clay584 Thanks for sharing this, I've updated ihac-fileget with the functionality you outlined. However at some point I assume it will be quicker to download the qkview and extract the files manually.

I'll close the issue for now
